# Generated by Django 2.2.5 on 2019-10-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specialist',
            new_name='Specialists',
        ),
    ]
