// SPECIALISTS
export const GET_SPECIALISTS = "GET_SPECIALISTS";
export const DELETE_SPECIALIST = "DELETE_SPECIALIST";
export const ADD_SPECIALIST = "ADD_SPECIALIST";

// ERRORS
export const GET_ERRORS = "GET_ERRORS";

// MESSAGES
export const CREATE_MESSAGE = "CREATE_MESSAGE";

// AUTH
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

