// SPECIALISTS
export const GET_SPECIALISTS = "GET_SPECIALISTS";
export const DELETE_SPECIALIST = "DELETE_SPECIALIST";
export const ADD_SPECIALIST = "ADD_SPECIALIST";

// ERRORS
export const GET_ERRORS = "GET_ERRORS";

// MESSAGES
export const CREATE_MESSAGE = "CREATE_MESSAGE";
